# Enter your hub server name here. This is where players will be sent to.
hub-server: "hub"

# Should we wait x amount of seconds before teleporting?
# Set to 0 to disable.
wait-time: 5

# Send this message when they use /hub. Leave it blank for no message.
send-message: "<red>Teleporting to the hub in {{SECONDS}} seconds!</red>"

# Do not touch please :)
config-version: 2