name: SimpleHub
version: ${project.version}
main: lol.hyper.simplehub.SimpleHubBukkit
api-version: 1.13
author: hyperdefined
commands:
  hub:
    description: Teleport back to the hub.
  reloadhub:
    description: Reload SimpleHub config.
permissions:
  simplehub.reload:
    default: op
    description: Allows the usage of /reloadhub